import fs from "fs";
import path from "path";
import type { Compiler } from "webpack";

interface CliPluginMeta {
  name: string;
  key: string;
  label: string;
  persona: "ops" | "dev";
}

interface CliPluginRegistryPluginOptions {
  assetsHost: string;
  plugins: CliPluginMeta[];
}

export class CliPluginRegistryPlugin {
  private options: CliPluginRegistryPluginOptions;

  constructor(options: CliPluginRegistryPluginOptions) {
    this.options = options;
  }

  apply(compiler: Compiler) {
    compiler.hooks.afterEmit.tapAsync(
      "CliPluginRegistryPlugin",
      (compilation, callback) => {
        const outputPath = compilation.outputOptions.path;
        if (!outputPath) {
          callback();
          return;
        }

        const metaByName = new Map(
          this.options.plugins.map((p) => [p.name, p]),
        );

        const registry: Record<string, unknown> = {
          assetsHost: this.options.assetsHost,
          plugins: {} as Record<string, unknown>,
        };

        const plugins = registry.plugins as Record<string, unknown>;

        // Read the mf-manifest.json generated by Module Federation
        const manifestPath = path.join(outputPath, "mf-manifest.json");
        let manifest: Record<string, unknown>;
        try {
          manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
        } catch {
          console.warn(
            "CliPluginRegistryPlugin: mf-manifest.json not found, skipping",
          );
          callback();
          return;
        }

        const pluginName = manifest.name as string | undefined;
        if (!pluginName) {
          callback();
          return;
        }

        const meta = metaByName.get(pluginName);
        if (!meta) {
          console.warn(
            `CliPluginRegistryPlugin: no metadata for plugin "${pluginName}"`,
          );
          callback();
          return;
        }

        const metaData = manifest.metaData as Record<string, unknown>;
        const remoteEntry = metaData?.remoteEntry as Record<string, unknown>;

        plugins[pluginName] = {
          name: meta.name,
          key: meta.key,
          label: meta.label,
          persona: meta.persona,
          mfManifest: {
            name: pluginName,
            remoteEntry: remoteEntry?.name,
            remoteEntryType: remoteEntry?.type,
            exposes: (manifest.exposes as Array<Record<string, unknown>>)?.map(
              (e) => ({
                name: e.name,
                path: e.path,
              }),
            ),
          },
        };

        const registryPath = path.join(outputPath, "cli-plugin-registry.json");
        try {
          fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2));
          console.log(`CLI plugin registry written: ${registryPath}`);
        } catch (err) {
          console.error(
            "CliPluginRegistryPlugin: failed to write registry",
            err,
          );
        }

        callback();
      },
    );
  }
}
