import type { ExtendedTemplateConfig } from "@patternfly/widgetized-dashboard";

export const LAYOUT_VERSION = 8;
const STORAGE_KEY = "fleetshift:dashboard-layout";
const VERSION_KEY = "fleetshift:dashboard-layout-version";

export function loadTemplate(): ExtendedTemplateConfig | null {
  try {
    const ver = localStorage.getItem(VERSION_KEY);
    if (Number(ver) !== LAYOUT_VERSION) return null;
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

export function saveTemplate(template: ExtendedTemplateConfig) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(template));
    localStorage.setItem(VERSION_KEY, String(LAYOUT_VERSION));
  } catch {
    // Best-effort persistence — don't break UI on quota errors
  }
}

export const defaultTemplate: ExtendedTemplateConfig = {
  xl: [
    {
      i: "slo-error-budgets#1",
      x: 0,
      y: 0,
      w: 2,
      h: 6,
      widgetType: "slo-error-budgets",
      title: "SLO Error Budgets",
    },
    {
      i: "fleet-health-grouped#1",
      x: 2,
      y: 0,
      w: 1,
      h: 6,
      widgetType: "fleet-health-grouped",
      title: "Fleet Health by Group",
    },
    {
      i: "compliance-status#1",
      x: 3,
      y: 0,
      w: 1,
      h: 6,
      widgetType: "compliance-status",
      title: "Compliance Status",
    },
    {
      i: "global-map#1",
      x: 0,
      y: 6,
      w: 2,
      h: 6,
      widgetType: "global-map",
      title: "Global Cluster Map",
    },
    {
      i: "version-distribution#1",
      x: 2,
      y: 6,
      w: 2,
      h: 6,
      widgetType: "version-distribution",
      title: "Version Distribution",
    },
    {
      i: "fleet-capacity#1",
      x: 0,
      y: 12,
      w: 2,
      h: 5,
      widgetType: "fleet-capacity",
      title: "Fleet Capacity",
    },
    {
      i: "active-incidents#1",
      x: 2,
      y: 12,
      w: 2,
      h: 5,
      widgetType: "active-incidents",
      title: "Active Incidents",
    },
    {
      i: "clusters-attention#1",
      x: 0,
      y: 17,
      w: 2,
      h: 4,
      widgetType: "clusters-attention",
      title: "Clusters Needing Attention",
    },
    {
      i: "mttr-trend#1",
      x: 2,
      y: 17,
      w: 2,
      h: 4,
      widgetType: "mttr-trend",
      title: "Mean Time to Resolution",
    },
  ],
  lg: [
    {
      i: "slo-error-budgets#1",
      x: 0,
      y: 0,
      w: 2,
      h: 6,
      widgetType: "slo-error-budgets",
      title: "SLO Error Budgets",
    },
    {
      i: "fleet-health-grouped#1",
      x: 2,
      y: 0,
      w: 1,
      h: 6,
      widgetType: "fleet-health-grouped",
      title: "Fleet Health by Group",
    },
    {
      i: "global-map#1",
      x: 0,
      y: 6,
      w: 2,
      h: 6,
      widgetType: "global-map",
      title: "Global Cluster Map",
    },
    {
      i: "version-distribution#1",
      x: 2,
      y: 6,
      w: 1,
      h: 6,
      widgetType: "version-distribution",
      title: "Version Distribution",
    },
    {
      i: "compliance-status#1",
      x: 0,
      y: 12,
      w: 1,
      h: 4,
      widgetType: "compliance-status",
      title: "Compliance Status",
    },
    {
      i: "active-incidents#1",
      x: 1,
      y: 12,
      w: 2,
      h: 4,
      widgetType: "active-incidents",
      title: "Active Incidents",
    },
    {
      i: "fleet-capacity#1",
      x: 0,
      y: 16,
      w: 2,
      h: 5,
      widgetType: "fleet-capacity",
      title: "Fleet Capacity",
    },
    {
      i: "clusters-attention#1",
      x: 2,
      y: 16,
      w: 1,
      h: 5,
      widgetType: "clusters-attention",
      title: "Clusters Needing Attention",
    },
    {
      i: "mttr-trend#1",
      x: 0,
      y: 21,
      w: 3,
      h: 5,
      widgetType: "mttr-trend",
      title: "Mean Time to Resolution",
    },
  ],
  md: [
    {
      i: "slo-error-budgets#1",
      x: 0,
      y: 0,
      w: 2,
      h: 6,
      widgetType: "slo-error-budgets",
      title: "SLO Error Budgets",
    },
    {
      i: "fleet-health-grouped#1",
      x: 0,
      y: 6,
      w: 1,
      h: 5,
      widgetType: "fleet-health-grouped",
      title: "Fleet Health by Group",
    },
    {
      i: "compliance-status#1",
      x: 1,
      y: 6,
      w: 1,
      h: 5,
      widgetType: "compliance-status",
      title: "Compliance Status",
    },
    {
      i: "global-map#1",
      x: 0,
      y: 11,
      w: 2,
      h: 6,
      widgetType: "global-map",
      title: "Global Cluster Map",
    },
    {
      i: "version-distribution#1",
      x: 0,
      y: 17,
      w: 2,
      h: 5,
      widgetType: "version-distribution",
      title: "Version Distribution",
    },
    {
      i: "fleet-capacity#1",
      x: 0,
      y: 22,
      w: 2,
      h: 5,
      widgetType: "fleet-capacity",
      title: "Fleet Capacity",
    },
    {
      i: "active-incidents#1",
      x: 0,
      y: 27,
      w: 2,
      h: 4,
      widgetType: "active-incidents",
      title: "Active Incidents",
    },
    {
      i: "clusters-attention#1",
      x: 0,
      y: 31,
      w: 2,
      h: 5,
      widgetType: "clusters-attention",
      title: "Clusters Needing Attention",
    },
    {
      i: "mttr-trend#1",
      x: 0,
      y: 36,
      w: 2,
      h: 5,
      widgetType: "mttr-trend",
      title: "Mean Time to Resolution",
    },
  ],
  sm: [
    {
      i: "slo-error-budgets#1",
      x: 0,
      y: 0,
      w: 1,
      h: 5,
      widgetType: "slo-error-budgets",
      title: "SLO Error Budgets",
    },
    {
      i: "fleet-health-grouped#1",
      x: 0,
      y: 5,
      w: 1,
      h: 5,
      widgetType: "fleet-health-grouped",
      title: "Fleet Health by Group",
    },
    {
      i: "compliance-status#1",
      x: 0,
      y: 10,
      w: 1,
      h: 3,
      widgetType: "compliance-status",
      title: "Compliance Status",
    },
    {
      i: "global-map#1",
      x: 0,
      y: 13,
      w: 1,
      h: 6,
      widgetType: "global-map",
      title: "Global Cluster Map",
    },
    {
      i: "version-distribution#1",
      x: 0,
      y: 19,
      w: 1,
      h: 5,
      widgetType: "version-distribution",
      title: "Version Distribution",
    },
    {
      i: "fleet-capacity#1",
      x: 0,
      y: 24,
      w: 1,
      h: 5,
      widgetType: "fleet-capacity",
      title: "Fleet Capacity",
    },
    {
      i: "active-incidents#1",
      x: 0,
      y: 29,
      w: 1,
      h: 4,
      widgetType: "active-incidents",
      title: "Active Incidents",
    },
    {
      i: "clusters-attention#1",
      x: 0,
      y: 33,
      w: 1,
      h: 5,
      widgetType: "clusters-attention",
      title: "Clusters Needing Attention",
    },
    {
      i: "mttr-trend#1",
      x: 0,
      y: 38,
      w: 1,
      h: 5,
      widgetType: "mttr-trend",
      title: "Mean Time to Resolution",
    },
  ],
};
